# Generated by Django 2.2.2 on 2019-06-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('folio', models.IntegerField()),
                ('issuing_rut', models.CharField(max_length=15)),
                ('issuing_name', models.CharField(max_length=30)),
                ('receiver_rut', models.CharField(max_length=15)),
                ('receiver_name', models.CharField(max_length=30)),
                ('detail', models.TextField(default='{}')),
            ],
        ),
    ]
